#
# This file lists the tasks that are executed on the host1 of a cPoP cluster to install a FRR service.
#
---

#
# FRR config
#

- name: Configure BGP neighbors
  frr_bgp:
    config:
      bgp_as: 64496
      neighbors:
        - neighbor: 192.0.2.10
          remote_as: 64496
          password: ansible
          description: IBGP_NBR_1
          timers:
            keepalive: 120
            holdtime: 360
        - neighbor: 192.0.2.15
          remote_as: 64496
          description: IBGP_NBR_2
          advertisement_interval: 120
    operation: merge



- name: Collect all facts
  become: yes
  setup:
    gather_subset:
      - '!all'
      - '!any'
  register: allfacts

- name: Network intefaces selection python script
  become: yes
  script: network-conf.py {{ ansible_facts }}
  register: output

- debug: var=output.stdout_lines

- debug:
    msg:
    - "1---- Network interfaces: {{ ansible_interfaces }}"
    - "2---- inventory_hostname: {{ inventory_hostname }}"

- debug:
    msg: "{{ ansible_facts | dict2items | selectattr('value.macaddress', 'defined') | map(attribute='value') }}"
  register: interfaces_facts

- debug:
    msg: "{% set output = [] %}\
        {% for result in interfaces_facts %}\
          {{ output.append( result ~ ' - ' ~ result) }}\
        {% endfor %}\
      {{ output }}"

- debug:
    msg: "{% set output = [] %}\
        {% for result in interfaces_facts %}\
          {{ output.append( result.macaddress ~ ' - ' ~ result.interface) }}\
        {% endfor %}\
      {{ output }}"

- name: define traditional ethernet facts
  set_fact:
    ansible_eth: "{% set ansible_eth = ansible_eth|default([]) + [hostvars[inventory_hostname]['ansible_' + item]] %}{{ ansible_eth|list }}"
  when: hostvars[inventory_hostname]['ansible_' + item]['type'] == 'ether'
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_interfaces'] }}"