#
# This file lists the tasks that are executed on the Proxmox VE cluster of a cPoP cluster to instantiate all VMs templates.
#
---

# Upload debian template for the vrf container

# - name: Upload debian template
#  become: yes
#  shell: |
#    pveam update
#    pveam download local debian-10.0-standard_10.0-1_amd64.tar.gz

# Create the vrf container template
- name: Create the vrf container template
  become: yes
  proxmox:
    vmid: "{{ host1_vm3_vid }}"
    node: "{{ host1_host_hostname }}"
    api_user: root@pam
    api_password: ProxmoxCp0p
    api_host: "{{ host1_host_fqdn }}"
    password: ProxmoxCp0p
    hostname: "{{ host1_vrf1_hostname }}"
    cores: "{{ host1_vm3_cpu }}"
    #cpus: "{{ host1_vm3_cpu }}"
    disk: "{{ host1_vm3_osdisk_size }}"
    memory: "{{ host1_vm3_ram }}"
    swap: "{{ host1_vm3_ram }}"
    nameserver: "{{ DNS_primary_ip4 }}"
    onboot: yes
    pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFYolCFdSV7sXlavem8hHZwV5OaZprCSM8eCHNOsHXcunYuJ4exuPk/0weIkYLUO8hK4ORLl+0xM7hClAQ8rcDU9w1ezVIlaZBYUQ/UJtj8tX9pTbTEaOBcDsSI1kW8xUiL/YTUbu1O8rKp4168pY9ClP3YAd0SRhuYjL0WilxsfvgPC1XHBfvfPQzL5YggFLPDLCw45EBf8CeGcslSONWyCiwlp2/IroNG0nyd/MHotGdMijUvTHYvJ0Ey0/fTDtksoMviD2/hFl/Pf8VQUe8WZApPHOWoSbNicFZl82IaqLEYAWctJh6FO2YSkItjNYXxzlzl7ledRG1a8mPlvAx yann.adam@orange.com'
    searchdomain: "{{ DNS_searchdomain }}"
    storage: local-data
    ostemplate: 'local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz'
    netif: '{"net0":"name=eth0,hwaddr={{ host1_vrf1_mac_client }},gw={{ host1_vrf1_ip4gw }},ip={{ host1_vrf1_ip4ad_client }}/28,bridge={{ host1_vm3_nic0_bridge }}"}'
    
# Start the vrf container
- name: Start the vrf container
  become: yes
  proxmox:
    vmid: "{{ host1_vm3_vid }}"
    api_user: root@pam
    api_password: ProxmoxCp0p
    api_host: "{{ host1_host_fqdn }}"
    state: started